### ISSUE TITLE
Segment7Display.cpp:194:36: error: 'dtostre' was not declared in this scope

### ISSUE THREAD

**Issue by Joennuh** [FinesseRus/Segment7Display#1]
When I try to compile the [USBdisplay](https://github.com/Finesse/Segment7Display/blob/master/examples/USBDisplay/USBDisplay.ino) example for my Wemos D1 mini I got this error:
```
C:\Users\*****\Documents\Arduino\libraries\Segment7Display-master\Segment7Display.cpp: In member function 'void Segment7Display::printFloat(float, unsigned char, boolean, byte, boolean, int, int)':

C:\Users\*****\Documents\Arduino\libraries\Segment7Display-master\Segment7Display.cpp:194:36: error: 'dtostre' was not declared in this scope

   dtostre(num, str, precision, 0x04);

                                    ^
```
I'm quite new to Arduino and don't understand all the stuff yet but could it be that `dtostre` needs to be `dtostrf`? Or should Arduino have a function called `dtostre`?

**Comment by Finesse** [comment]
`dtostre` is used intentionally to print number in the exponential form (e.g. `1.23E04`). It's a part of the avr-libc library designed for Atmel AVR microcontrollers (which are used in Arduino devices).

The simplest advice I can give is to remove the `dtostre` function call in your library copy. Open `C:\Users\*****\Documents\Arduino\libraries\Segment7Display-master\Segment7Display.cpp` and make the following substitution:

```diff
	char *str = new char[maxLength];

-	if(E) {
-		dtostre(num, str, precision, DTOSTR_UPPERCASE);
-		for(int i = 0; i < maxLength - 1; ++i)
-			if(str[i] == 'E') {
-				if(str[++i] == '+') {
-					for(; i < maxLength - 1; ++i)
-						str[i] = str[i + 1];
-					str[i] = 0;
-				}
-				break;
-			}
-	} else
-		dtostrf(num, 1, precision, str);
+	dtostrf(num, 1, precision, str);

	printString(str, align, clearExcess, offset, maxLength);
```

I guess there is a way to declare the `dtostre` function when it's not defined, but I don't have much experience in C++ so I can't do it.

The error happens not on Arduino so I close the issue for now.

**Comment by Finesse** [comment]
@Joennuh Can you do the following substitution and tell me the result?

```diff
	char *str = new char[maxLength];

	if(E) {
+		#if defined(ARDUINO)
		dtostre(num, str, precision, DTOSTR_UPPERCASE);
		for(int i = 0; i < maxLength - 1; ++i)
			if(str[i] == 'E') {
				if(str[++i] == '+') {
					for(; i < maxLength - 1; ++i)
						str[i] = str[i + 1];
					str[i] = 0;
				}
				break;
			}
+		#endif
	} else
		dtostrf(num, 1, precision, str);

	printString(str, align, clearExcess, offset, maxLength);
```

**Comment by Joennuh** [comment]
The first solution works. The second solution does produce the same error as before.
